export const START = "/";
export const HOME = "/home"; // да простят меня боги за этот костыль
export const SHOP = "/shop";
export const SHOP_CODE = `${ SHOP }/:code`;
export const PRODUCT = "/product";
export const PRODUCT_CODE = `${ PRODUCT }/:code`;
export const CART = "/cart";
export const CHECKOUT = "/checkout";
export const ABOUT = '/about';
export const ABOUT_CODE = `${ ABOUT }/:code`;
export const SUCCESS= "/success";
